### ISSUE TITLE
Failed to fetch plugin cordova-plugin-googleplayservices@21.0.0 via registry

### ISSUE THREAD

**Issue by jmgomezpoveda** [cranberrygame/cordova-plugin-game#10]
When trying to install the plugin I get the following error:

Installing "cordova-plugin-game" for android
Notice: com.google.playservices@21.0.0 has been automatically converted to cordova-plugin-googleplayservices and fetched from npm. This is due to our old plugins registry shutting down.
Fetching plugin "cordova-plugin-googleplayservices@21.0.0" via npm
Failed to install 'cordova-plugin-game':Failed to fetch plugin cordova-plugin-googleplayservices@21.0.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: version not found: cordova-plugin-googleplayservices@21.0.0
    at registry.fetch.fail.then.pinfo (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:146:33)
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:415:13)

**Comment by cranberrygame** [comment]
@jmgomezpoveda 
Fix the issue.
Thanks

**Comment by jmgomezpoveda** [comment]
Thanks. There is a new error, though; not sure if related:

$ cordova plugin add cordova-plugin-game --variable APP_ID="GAME_APP_ID"
Fetching plugin "cordova-plugin-game" via npm
Installing "cordova-plugin-game" for android
Fetching plugin "cordova-plugin-extras-google-play-services" via npm
Installing "cordova-plugin-extras-google-play-services" for android
Fetching plugin "cordova-plugin-extras-android-support-library-v4" via npm
Installing "cordova-plugin-extras-android-support-library-v4" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-game':TypeError: Uh oh!
Object #<Object> has no method 'parse'
    at module.exports.common.js-module.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:131:71)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:653:27
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PlatformApiPoly.addPlugin (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:259:20)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:603:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:382:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
Error: Uh oh!
Object #<Object> has no method 'parse'

**Comment by cranberrygame** [comment]
@jmgomezpoveda 

Hi

Tested cordova plugin add cordova-plugin-game --variable APP_ID="GAME_APP_ID"
But no error.

Thanks
